root: true
reportUnusedDisableDirectives: true
parser: "@typescript-eslint/parser"

parserOptions:
  sourceType: module
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
  project: true

plugins:
  - "@eslint-react/eslint-plugin"
  - "@stylistic/eslint-plugin-jsx"
  - eslint-plugin-jsx-a11y
  - eslint-plugin-react
  - eslint-plugin-react-hooks
  - eslint-plugin-react-refresh
  - eslint-plugin-validate-jsx-nesting

settings:
  react:
    version: detect
  linkComponents:
    - name: Link
      linkAttribute: href

rules:
  "@eslint-react/ensure-forward-ref-using-ref": [0]
  "@eslint-react/no-access-state-in-setstate": [2]
  "@eslint-react/no-array-index-key": [0]
  "@eslint-react/no-children-count": [0]
  "@eslint-react/no-children-for-each": [0]
  "@eslint-react/no-children-map": [0]
  "@eslint-react/no-children-only": [0]
  "@eslint-react/no-children-prop": [0]
  "@eslint-react/no-children-to-array": [0]
  "@eslint-react/no-class-component": [0]
  "@eslint-react/no-clone-element": [0]
  "@eslint-react/no-comment-textnodes": [2]
  "@eslint-react/no-complicated-conditional-rendering": [0]
  "@eslint-react/no-component-will-mount": [0]
  "@eslint-react/no-component-will-receive-props": [0]
  "@eslint-react/no-component-will-update": [0]
  "@eslint-react/no-create-ref": [2]
  "@eslint-react/no-direct-mutation-state": [2]
  "@eslint-react/no-duplicate-key": [2]
  "@eslint-react/no-implicit-key": [2]
  "@eslint-react/no-leaked-conditional-rendering": [0]
  "@eslint-react/no-missing-component-display-name": [0]
  "@eslint-react/no-missing-key": [2]
  "@eslint-react/no-nested-components": [2]
  "@eslint-react/no-redundant-should-component-update": [0]
  "@eslint-react/no-set-state-in-component-did-mount": [0]
  "@eslint-react/no-set-state-in-component-did-update": [0]
  "@eslint-react/no-set-state-in-component-will-update": [0]
  "@eslint-react/no-string-refs": [2]
  "@eslint-react/no-unsafe-component-will-mount": [0]
  "@eslint-react/no-unsafe-component-will-receive-props": [0]
  "@eslint-react/no-unsafe-component-will-update": [0]
  "@eslint-react/no-unstable-context-value": [0]
  "@eslint-react/no-unstable-default-props": [2]
  "@eslint-react/no-unused-class-component-members": [2]
  "@eslint-react/no-unused-state": [2]
  "@eslint-react/no-useless-fragment": [2]
  "@eslint-react/prefer-destructuring-assignment": [0]
  "@eslint-react/prefer-shorthand-boolean": [0]
  "@eslint-react/prefer-shorthand-fragment": [0]
  "@eslint-react/dom/no-children-in-void-dom-elements": [2]
  "@eslint-react/dom/no-dangerously-set-innerhtml": [0]
  "@eslint-react/dom/no-dangerously-set-innerhtml-with-children": [2]
  "@eslint-react/dom/no-find-dom-node": [0]
  "@eslint-react/dom/no-missing-button-type": [0]
  "@eslint-react/dom/no-missing-iframe-sandbox": [0]
  "@eslint-react/dom/no-namespace": [2]
  "@eslint-react/dom/no-render-return-value": [2]
  "@eslint-react/dom/no-script-url": [2]
  "@eslint-react/dom/no-unsafe-iframe-sandbox": [0]
  "@eslint-react/dom/no-unsafe-target-blank": [0]
  "@eslint-react/hooks-extra/ensure-custom-hooks-using-other-hooks": [0]
  "@eslint-react/hooks-extra/ensure-use-callback-has-non-empty-deps": [0]
  "@eslint-react/hooks-extra/ensure-use-memo-has-non-empty-deps": [0]
  "@eslint-react/hooks-extra/prefer-use-state-lazy-initialization": [0]
  "@eslint-react/naming-convention/component-name": [0]
  "@eslint-react/naming-convention/filename": [0]
  "@eslint-react/naming-convention/filename-extension": [0]
  "@eslint-react/naming-convention/use-state": [2]
  "@stylistic/jsx/jsx-child-element-spacing": [0]
  "@stylistic/jsx/jsx-closing-bracket-location": [0]
  "@stylistic/jsx/jsx-closing-tag-location": [2]
  "@stylistic/jsx/jsx-curly-brace-presence": [2, {props: never, children: never, propElementValues: always}]
  "@stylistic/jsx/jsx-curly-newline": [2, consistent]
  "@stylistic/jsx/jsx-curly-spacing": [2, {when: never}]
  "@stylistic/jsx/jsx-equals-spacing": [2, never]
  "@stylistic/jsx/jsx-first-prop-new-line": [0]
  "@stylistic/jsx/jsx-indent": [2, 2, {checkAttributes: true, indentLogicalExpressions: true}]
  "@stylistic/jsx/jsx-indent-props": [2, 2]
  "@stylistic/jsx/jsx-max-props-per-line": [0]
  "@stylistic/jsx/jsx-newline": [0]
  "@stylistic/jsx/jsx-one-expression-per-line": [0]
  "@stylistic/jsx/jsx-pascal-case": [2, {allowAllCaps: true}]
  "@stylistic/jsx/jsx-props-no-multi-spaces": [2]
  "@stylistic/jsx/jsx-self-closing-comp": [2]
  "@stylistic/jsx/jsx-sort-props": [0]
  "@stylistic/jsx/jsx-tag-spacing": [2, {beforeSelfClosing: never, beforeClosing: never}]
  "@stylistic/jsx/jsx-wrap-multilines": [2]
  jsx-a11y/accessible-emoji: [0]
  jsx-a11y/alt-text: [0]
  jsx-a11y/anchor-ambiguous-text: [2]
  jsx-a11y/anchor-has-content: [2]
  jsx-a11y/anchor-is-valid: [2]
  jsx-a11y/aria-activedescendant-has-tabindex: [2]
  jsx-a11y/aria-props: [2]
  jsx-a11y/aria-proptypes: [2]
  jsx-a11y/aria-role: [2]
  jsx-a11y/aria-unsupported-elements: [2]
  jsx-a11y/autocomplete-valid: [2]
  jsx-a11y/click-events-have-key-events: [0]
  jsx-a11y/control-has-associated-label: [0]
  jsx-a11y/heading-has-content: [2]
  jsx-a11y/html-has-lang: [0]
  jsx-a11y/iframe-has-title: [0]
  jsx-a11y/img-redundant-alt: [0]
  jsx-a11y/interactive-supports-focus: [0]
  jsx-a11y/label-has-associated-control: [2]
  jsx-a11y/label-has-for: [0]
  jsx-a11y/lang: [2]
  jsx-a11y/media-has-caption: [0]
  jsx-a11y/mouse-events-have-key-events: [0]
  jsx-a11y/no-access-key: [2]
  jsx-a11y/no-aria-hidden-on-focusable: [0]
  jsx-a11y/no-autofocus: [0]
  jsx-a11y/no-distracting-elements: [2]
  jsx-a11y/no-interactive-element-to-noninteractive-role: [0]
  jsx-a11y/no-noninteractive-element-interactions: [0]
  jsx-a11y/no-noninteractive-element-to-interactive-role: [0]
  jsx-a11y/no-noninteractive-tabindex: [0]
  jsx-a11y/no-onchange: [0]
  jsx-a11y/no-redundant-roles: [2]
  jsx-a11y/no-static-element-interactions: [0]
  jsx-a11y/prefer-tag-over-role: [0]
  jsx-a11y/role-has-required-aria-props: [2]
  jsx-a11y/role-supports-aria-props: [2]
  jsx-a11y/scope: [0]
  jsx-a11y/tabindex-no-positive: [2]
  react-hooks/exhaustive-deps: [2]
  react-hooks/rules-of-hooks: [2]
  react-refresh/only-export-components: [2, {allowConstantExport: true}]
  react/boolean-prop-naming: [0]
  react/button-has-type: [0]
  react/default-props-match-prop-types: [0]
  react/destructuring-assignment: [0]
  react/display-name: [2]
  react/forbid-component-props: [0]
  react/forbid-dom-props: [0]
  react/forbid-elements: [0]
  react/forbid-foreign-prop-types: [0]
  react/forbid-prop-types: [0]
  react/function-component-definition: [0]
  react/hook-use-state: [2, {allowDestructuredState: true}]
  react/iframe-missing-sandbox: [0]
  react/jsx-boolean-value: [2, always]
  react/jsx-filename-extension: [2, {allow: as-needed, extensions: [.jsx,.tsx], ignoreFilesWithoutCode: true}]
  react/jsx-fragments: [2, element]
  react/jsx-handler-names: [0]
  react/jsx-key: [2, {warnOnDuplicates: true}]
  react/jsx-max-depth: [0]
  react/jsx-no-bind: [0]
  react/jsx-no-comment-textnodes: [2]
  react/jsx-no-constructed-context-values: [2]
  react/jsx-no-duplicate-props: [2]
  react/jsx-no-leaked-render: [0]
  react/jsx-no-literals: [0]
  react/jsx-no-script-url: [2, {includeFromSettings: true}]
  react/jsx-no-target-blank: [0]
  react/jsx-no-undef: [2]
  react/jsx-no-useless-fragment: [2, {allowExpressions: false}]
  react/jsx-pascal-case: [0] # covered by @stylistic/jsx/jsx-pascal-case
  react/jsx-props-no-spreading: [0]
  react/jsx-space-before-closing: [0]
  react/jsx-uses-react: [0]
  react/jsx-uses-vars: [2]
  react/no-access-state-in-setstate: [0]
  react/no-adjacent-inline-elements: [0]
  react/no-array-index-key: [0]
  react/no-arrow-function-lifecycle: [2]
  react/no-children-prop: [2]
  react/no-danger-with-children: [0]
  react/no-danger: [0]
  react/no-deprecated: [2]
  react/no-did-mount-set-state: [0]
  react/no-did-update-set-state: [0]
  react/no-direct-mutation-state: [0] # slow
  react/no-find-dom-node: [2]
  react/no-invalid-html-attribute: [2]
  react/no-is-mounted: [0]
  react/no-multi-comp: [0]
  react/no-namespace: [2]
  react/no-object-type-as-default-prop: [2]
  react/no-redundant-should-component-update: [2]
  react/no-render-return-value: [0]
  react/no-set-state: [0]
  react/no-string-refs: [2]
  react/no-this-in-sfc: [2]
  react/no-typos: [2]
  react/no-unescaped-entities: [2]
  react/no-unknown-property: [2, {ignore: [css], requireDataLowercase: true}]
  react/no-unsafe: [0]
  react/no-unused-class-component-methods: [2]
  react/no-unused-prop-types: [0]
  react/no-unused-state: [2]
  react/no-will-update-set-state: [0]
  react/prefer-es6-class: [0]
  react/prefer-exact-props: [0]
  react/prefer-read-only-props: [0]
  react/prefer-stateless-function: [0]
  react/prop-types: [0]
  react/react-in-jsx-scope: [0]
  react/require-default-props: [0]
  react/require-optimization: [0]
  react/require-render-return: [2]
  react/sort-comp: [0]
  react/sort-default-props: [0]
  react/sort-prop-types: [0]
  react/state-in-constructor: [0]
  react/static-property-placement: [0]
  react/style-prop-object: [2]
  react/void-dom-elements-no-children: [2]
  validate-jsx-nesting/no-invalid-jsx-nesting: [2]
