root: true
reportUnusedDisableDirectives: true

parserOptions:
  sourceType: module
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true

plugins:
  - eslint-plugin-jsx-a11y
  - eslint-plugin-react
  - eslint-plugin-react-hooks
  - eslint-plugin-react-refresh
  - eslint-plugin-validate-jsx-nesting

settings:
  react:
    version: detect

rules:
  jsx-a11y/accessible-emoji: [0]
  jsx-a11y/alt-text: [0]
  jsx-a11y/anchor-ambiguous-text: [2]
  jsx-a11y/anchor-has-content: [2]
  jsx-a11y/anchor-is-valid: [2]
  jsx-a11y/aria-activedescendant-has-tabindex: [2]
  jsx-a11y/aria-props: [2]
  jsx-a11y/aria-proptypes: [2]
  jsx-a11y/aria-role: [2]
  jsx-a11y/aria-unsupported-elements: [2]
  jsx-a11y/autocomplete-valid: [2]
  jsx-a11y/click-events-have-key-events: [0]
  jsx-a11y/control-has-associated-label: [0]
  jsx-a11y/heading-has-content: [2]
  jsx-a11y/html-has-lang: [0]
  jsx-a11y/iframe-has-title: [0]
  jsx-a11y/img-redundant-alt: [0]
  jsx-a11y/interactive-supports-focus: [0]
  jsx-a11y/label-has-associated-control: [2]
  jsx-a11y/label-has-for: [0]
  jsx-a11y/lang: [2]
  jsx-a11y/media-has-caption: [0]
  jsx-a11y/mouse-events-have-key-events: [0]
  jsx-a11y/no-access-key: [2]
  jsx-a11y/no-aria-hidden-on-focusable: [0]
  jsx-a11y/no-autofocus: [0]
  jsx-a11y/no-distracting-elements: [2]
  jsx-a11y/no-interactive-element-to-noninteractive-role: [0]
  jsx-a11y/no-noninteractive-element-interactions: [0]
  jsx-a11y/no-noninteractive-element-to-interactive-role: [0]
  jsx-a11y/no-noninteractive-tabindex: [0]
  jsx-a11y/no-onchange: [0]
  jsx-a11y/no-redundant-roles: [2]
  jsx-a11y/no-static-element-interactions: [0]
  jsx-a11y/prefer-tag-over-role: [0]
  jsx-a11y/role-has-required-aria-props: [2]
  jsx-a11y/role-supports-aria-props: [2]
  jsx-a11y/scope: [0]
  jsx-a11y/tabindex-no-positive: [2]
  react-hooks/exhaustive-deps: [2]
  react-hooks/rules-of-hooks: [2]
  react-refresh/only-export-components: [0, {allowConstantExport: true}]
  react/boolean-prop-naming: [0]
  react/button-has-type: [0]
  react/default-props-match-prop-types: [0]
  react/destructuring-assignment: [0]
  react/display-name: [2]
  react/forbid-component-props: [0]
  react/forbid-dom-props: [0]
  react/forbid-elements: [0]
  react/forbid-foreign-prop-types: [0]
  react/forbid-prop-types: [0]
  react/function-component-definition: [0]
  react/hook-use-state: [2, {allowDestructuredState: true}]
  react/iframe-missing-sandbox: [0]
  react/jsx-boolean-value: [2, always]
  react/jsx-child-element-spacing: [0]
  react/jsx-closing-bracket-location: [0]
  react/jsx-closing-tag-location: [0]
  react/jsx-curly-brace-presence: [0]
  react/jsx-curly-newline: [2, consistent]
  react/jsx-curly-spacing: [2, {when: never}]
  react/jsx-equals-spacing: [2, never]
  react/jsx-filename-extension: [2, {allow: as-needed, extensions: [.jsx,.tsx]}]
  react/jsx-first-prop-new-line: [0]
  react/jsx-fragments: [2, element]
  react/jsx-handler-names: [0]
  react/jsx-indent-props: [2, 2]
  react/jsx-indent: [2, 2, {checkAttributes: true, indentLogicalExpressions: true}]
  react/jsx-key: [2, {warnOnDuplicates: true}]
  react/jsx-max-depth: [0]
  react/jsx-max-props-per-line: [0]
  react/jsx-newline: [0]
  react/jsx-no-bind: [0]
  react/jsx-no-comment-textnodes: [2]
  react/jsx-no-constructed-context-values: [2]
  react/jsx-no-duplicate-props: [2]
  react/jsx-no-leaked-render: [0]
  react/jsx-no-literals: [0]
  react/jsx-no-script-url: [2]
  react/jsx-no-target-blank: [0]
  react/jsx-no-undef: [2]
  react/jsx-no-useless-fragment: [2, {allowExpressions: false}]
  react/jsx-one-expression-per-line: [0]
  react/jsx-pascal-case: [2, {allowAllCaps: true}]
  react/jsx-props-no-multi-spaces: [2]
  react/jsx-props-no-spreading: [0]
  react/jsx-sort-props: [0]
  react/jsx-space-before-closing: [0]
  react/jsx-tag-spacing: [2, {beforeSelfClosing: never, beforeClosing: never}]
  react/jsx-uses-react: [0]
  react/jsx-uses-vars: [2]
  react/jsx-wrap-multilines: [2]
  react/no-access-state-in-setstate: [0]
  react/no-adjacent-inline-elements: [0]
  react/no-array-index-key: [0]
  react/no-arrow-function-lifecycle: [2]
  react/no-children-prop: [2]
  react/no-danger-with-children: [0]
  react/no-danger: [0]
  react/no-deprecated: [2]
  react/no-did-mount-set-state: [0]
  react/no-did-update-set-state: [0]
  react/no-direct-mutation-state: [2]
  react/no-find-dom-node: [2]
  react/no-invalid-html-attribute: [2]
  react/no-is-mounted: [0]
  react/no-multi-comp: [0]
  react/no-namespace: [2]
  react/no-object-type-as-default-prop: [2]
  react/no-redundant-should-component-update: [2]
  react/no-render-return-value: [0]
  react/no-set-state: [0]
  react/no-string-refs: [2]
  react/no-this-in-sfc: [2]
  react/no-typos: [2]
  react/no-unescaped-entities: [2]
  react/no-unknown-property: [2, {ignore: [css]}]
  react/no-unsafe: [0]
  react/no-unused-class-component-methods: [2]
  react/no-unused-prop-types: [0]
  react/no-unused-state: [2]
  react/no-will-update-set-state: [0]
  react/prefer-es6-class: [0]
  react/prefer-exact-props: [0]
  react/prefer-read-only-props: [0]
  react/prefer-stateless-function: [0]
  react/prop-types: [0]
  react/react-in-jsx-scope: [0]
  react/require-default-props: [0]
  react/require-optimization: [0]
  react/require-render-return: [2]
  react/self-closing-comp: [2]
  react/sort-comp: [0]
  react/sort-default-props: [0]
  react/sort-prop-types: [0]
  react/state-in-constructor: [0]
  react/static-property-placement: [0]
  react/style-prop-object: [2]
  react/void-dom-elements-no-children: [2]
  validate-jsx-nesting/no-invalid-jsx-nesting: [2]
